 
module.exports = {
    food: [
        "molasses",
        "grits",
        "snapper",
        "caviar",
        "mustard",
        "succotash",
        "duck",
        "ketchup",
        "cannellini beans",
        "coffee",
        "brown sugar",
        "celery seeds",
        "peanuts",
        "hoisin sauce",
        "orange peels",
        "maraschino cherries",
        "panko bread crumbs",
        "broth",
        "chicory",
        "walnuts",
        "brazil nuts",
        "corned beef",
        "artichokes",
        "geese",
        "pecans",
        "water",
        "Parmesan cheese",
        "kumquats",
        "lemons",
        "pumpkin seeds",
        "honeydew melons",
        "borscht",
        "ginger",
        "aioli",
        "green onions",
        "swordfish",
        "red cabbage",
        "asparagus",
        "raisins",
        "catfish",
        "plums",
        "turnips",
        "andouille sausage",
        "baguette",
        "cheddar cheese",
        "plantains",
        "alfredo sauce",
        "coconuts",
        "hazelnuts",
        "garlic",
        "flour",
        "scallops",
        "sea cucumbers",
        "sweet potatoes",
        "apple pie spice",
        "garlic powder",
        "barley sugar",
        "cornstarch",
        "soybeans",
        "yogurt",
        "Cappuccino Latte",
        "macaroni",
        "bean threads",
        "coconut oil",
        "truffles",
        "venison",
        "snow peas",
        "okra",
        "watermelons",
        "split peas",
        "ham",
        "shitakes",
        "cranberries",
        "Kahlua",
        "chaurice sausage",
        "ginger ale",
        "chili powder",
        "crabs",
        "apple butter",
        "poppy seeds",
        "canola oil",
        "trout",
        "Worcestershire sauce",
        "water chestnuts",
        "lima beans",
        "anchovies",
        "guavas",
        "liver",
        "pepper",
        "artificial sweetener",
        "blueberries",
        "potato chips",
        "chard",
        "veal",
        "habanero chilies",
        "sausages",
        "Marsala",
        "tomato sauce",
        "clams",
        "oatmeal"    
    ],

    foodPhotos: [
        "https://i.imgur.com/bO7ve2X.png",
        "https://i.imgur.com/KgQ7K8u.jpg",
        "https://i.imgur.com/XNTwwy3.jpg",
        "https://i.imgur.com/8BXK6LO.jpg",
        "https://i.imgur.com/3I6uXiD.jpg",
        "https://i.imgur.com/ARvq9qm.jpg",
        "https://i.imgur.com/W4jcwUE.jpg",
        "https://i.imgur.com/xVmw92l.jpg",
        "https://i.imgur.com/4JdxjHm.jpg",
        "https://i.imgur.com/5NpSA7z.jpg"
    ]
}